### ISSUE TITLE
Manifest URL Installation Not Working

### ISSUE THREAD

**Issue by Talwynor** [ThroughlyDruxy/tor2e-npc-parser#17]
I receiving the following error when attempting to install:

setup.js:292 Error: An unexpected error occurred when downloading file https://github.com/ThroughlyDruxy/tor2e-npc-parser/releases/download/v0.5.3/tor2e-npc-parser.zip: Not Found
    at fetchWithTimeout (file:///D:/Foundry%20Virtual%20Tabletop-Local%20GM%20Instance/resources/app/common/utils/http.mjs:42:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///D:/Foundry%20Virtual%20Tabletop-Local%20GM%20Instance/resources/app/dist/files/downloader.mjs:1:616

**Comment by ThroughlyDruxy** [comment]
I think this is fixed now. I'll close the issue, if it reoccurs, please reopen it or message me on discord.
